### ISSUE TITLE
[Linux] Can't change install path.

### ISSUE THREAD

**Issue by Mrjelly13** [sqrldev/SQRLDotNetClient#103] opened 2020-04-13 04:06 UTC
Cannot change install directory and clicking the "Install Path..." Button crashes the installer.

This is the information shown in the terminal:
```
$ Installer Launched
$ Deltected Platform: Linux
$ Launched Version Selector
$ Current Download Size is : 62.88MB
$ Current Download URL is : https://github.com/sqrldev/SQRLDotNetClient/releases/download/v0.11-beta/linux-x64.zip
$ Found 3 Releases
$ Set Installation Path To: /home/ericreigle/SQRL
$ fish: “./SQRLPlatformAwareInstaller_li…” terminated by signal SIGSEGV (Address boundary error)
```
There's also a typo in there. `Deltected Platform: Linux`

**Comment by alexhauser** [comment] 2020-04-13 06:30
Thanks for reporting, @Mrjelly13. 

Unfortunately, I can't reproduce the error under Ubuntu 18.04.
Can you please provide a little more info on the system (OS and version)? Also, which release of the Installer did you download? Beta3?

**Comment by josegomez** [comment] 2020-04-13 14:40
@Mrjelly13 there should also be an installer log in that folder, can we get it?

**Comment by alexhauser** [comment] 2020-04-13 15:34
@Mrjelly13, googling for the error `SIGSEGV (Address boundary error)` brought up this error report for the "Fish shell": 

https://github.com/fish-shell/fish-shell/issues/5409

Since I can read `fish:` in your log output I suspect you are using that shell, and even though the error report above is from 2018, I still guess it might be related. Can you confirm?
(Maybe try a different shell?)

**Comment by Mrjelly13** [comment] 2020-04-13 15:45
@alexhauser I am using the fish shell, but I tested it using zsh as well. Got a similar error. I am running Manjaro Linux with the 5.6 kernel. I did download the Beta3 installer.
@josegomez Content of the installer log is pretty much identical to the terminal output minus the error
```
2020-04-13 11:39:53.441 -04:00 [INF] Installer Launched
2020-04-13 11:39:53.542 -04:00 [INF] Deltected Platform: Linux
2020-04-13 11:39:56.179 -04:00 [INF] Launched Version Selector
2020-04-13 11:40:02.044 -04:00 [INF] Current Download Size is : 62.88MB
2020-04-13 11:40:02.044 -04:00 [INF] Current Download URL is : https://github.com/sqrldev/SQRLDotNetClient/releases/download/v0.11-beta/linux-x64.zip
2020-04-13 11:40:02.044 -04:00 [INF] Found 3 Releases
2020-04-13 11:40:02.045 -04:00 [INF] Set Installation Path To: /home/ericreigle/SQRL
```

For reference, the install does work if I don't try to change the install path

**Comment by Mrjelly13** [comment] 2020-04-13 15:47
Here is the output using bash: 
```
$ Installer Launched
$ Deltected Platform: Linux
$ Launched Version Selector
$ Current Download Size is : 62.88MB
$ Current Download URL is : https://github.com/sqrldev/SQRLDotNetClient/releases/download/v0.11-beta/linux-x64.zip
$ Found 3 Releases
$ Set Installation Path To: /home/ericreigle/SQRL
$ Segmentation fault (core dumped)
```

**Comment by alexhauser** [comment] 2020-04-13 15:52
Ok, I guess we'll need a stack trace here.

@Mrjelly13, could you clone the repository and run the installer directly from source? If yes, please let me know and I'll include some code to make the log output more meaningful. Thanks in advance for your feedback.

**Comment by Mrjelly13** [comment] 2020-04-13 15:57
Sure. Let me know what I need for that and I'll give it a go.

**Comment by alexhauser** [comment] 2020-04-13 16:09
Great, @Mrjelly13 !

You'd have to install the .NET Core SDK:
https://docs.microsoft.com/en-us/dotnet/core/install/sdk?pivots=os-linux

Then install git, clone the repo, build and run:
```
git clone https://github.com/sqrldev/SQRLDotNetClient.git
cd SQRLDotNetClient/SQRLPlatformAwareInstaller
donet build && dotnet run
```

If that all works, let me know and I'll push some debug code.

**Comment by Mrjelly13** [comment] 2020-04-13 16:15
Ok, that all builds fine.

**Comment by alexhauser** [comment] 2020-04-13 16:24
Great! I've added some debug code to my current PR #104, I will merge it as soon as the unit tests have passed and then let you know when you can pull the changes and rebuild.

Thanks for your patience, @Mrjelly13!

**Comment by Mrjelly13** [comment] 2020-04-13 16:26
Sounds good, Happy to help! @alexhauser

**Comment by alexhauser** [comment] 2020-04-13 16:34
@Mrjelly13, everything is merged now.

Please do a `git pull` followed by a `dotnet build && dotnet run` while you're still in the installer directory.

The installer should then run. Just follow the steps and when hitting the "Install Path..." button now, the error log should be more verbose. Please post the output of that here.

**Comment by Mrjelly13** [comment] 2020-04-13 16:44
@alexhauser Unfortunately it wasn't any more helpful, maybe I'm missing something?
```
[12:41:35 INF] New app instance is being launched on Linux 5.6.3-2-MANJARO #1 SMP PREEMPT Wed Apr 8 20:57:18 UTC 2020
[12:41:35 INF] Installer main screen launched
[12:41:35 INF] Detected platform: Linux
[12:41:38 INF] Version selection screen launched
[12:41:39 INF] Current download size is : 62.88 MB
[12:41:39 INF] Current download URL is : https://github.com/sqrldev/SQRLDotNetClient/releases/download/v0.11-beta/linux-x64.zip
[12:41:39 INF] Found 3 Releases
[12:41:39 INF] Set installation path to: /home/ericreigle/SQRL
```

**Comment by alexhauser** [comment] 2020-04-13 16:52
@Mrjelly13, you're not missing anything, the fixed typo and the new log message showing the exact OS description tell me that you ARE definitely running the latest code.

It looks like that segfault just tears down everything and normal exception handling is useless in this case. Can't think of any quick fix right now, sorry. I guess it's more fundamental problem though, nothing that we could fix anyway - either in Avalonia (the UI framework that we're using) or even deeper in the .NET Core runtime.

I'll have to think about it some more.

**Comment by Mrjelly13** [comment] 2020-04-13 17:00
Ok @alexhauser, let let me know if you think of anything. If I have some time I'll see if I can find anything else on my end.

**Comment by josegomez** [comment] 2020-04-13 17:28
@Mrjelly13 , @alexhauser 
I've had this before on a Mac it had to do with the Avalonia Select Dialog call.

Likely related to this little guy on the linux side.
https://github.com/AvaloniaUI/Avalonia/issues/2817

**Comment by alexhauser** [comment] 2020-04-13 17:41
@josegomez, indeed, that seems to be it! Thanks! 👍🏻

As the bug seems to be located in a dependency of a dependency, all we can do at this point is wait for an update to eventually arrive downstream. Sorry, @Mrjelly13.

**Comment by josegomez** [comment] 2020-04-13 17:45
@Mrjelly13 just to be 100% certain  clone this project 
https://github.com/josegomez/SelectDialogTest.git
and run it, it should generate a Log.
It's just a form with a button on it to pick a dialog.
Just make sure it crashes the same way, and if the log contains anything else.

```
git clone https://github.com/josegomez/SelectDialogTest.git

cd SelectDialogTest

dotnet restore

donet build && dotnet run

```

**Comment by Mrjelly13** [comment] 2020-04-13 17:50
@josegomez I tried running it but I got the following error: `Couldn't find a project to run. Ensure a project exists in /tmp/SelectDialogTest, or pass the path to the project using --project.`

**Comment by josegomez** [comment] 2020-04-13 17:53
ah sorry @Mrjelly13 cd into SelectDialogTest again, I wasn't paying attention when I created the solution and it ended up in a different folder.
So the complete code should be
```
git clone https://github.com/josegomez/SelectDialogTest.git

cd SelectDialogTest
cd SelectDialogTest
dotnet restore
dotnet build && dotnet run
```

**Comment by Mrjelly13** [comment] 2020-04-13 18:12
Ok, so I ran it, but nothing happened. Just ran and then exited with nothing,

**Comment by josegomez** [comment] 2020-04-13 18:16
@Mrjelly13 
Right, but do you see anything in the log file?
SelectDialogTest\SelectDialogTest\bin\Debug\netcoreapp3.0\log20200413.txt

**Comment by Mrjelly13** [comment] 2020-04-13 18:20
@josegomez There's no log file there.

**Comment by josegomez** [comment] 2020-04-13 18:21
HMMM.... that's strange, so does the screen come up? and you select a dialog? and there is no log file?.... that's odd. 
STandby

**Comment by Mrjelly13** [comment] 2020-04-13 18:22
Nope, noting happens when I run it at all.

**Comment by josegomez** [comment] 2020-04-13 19:59
ok @Mrjelly13 I installed Manjaro can replicate. On Both Projects.
BTW I fixed the other project but it doesn't matter I can replicate and will open some issues for it.

**Comment by Mrjelly13** [comment] 2020-04-13 20:12
@josegomez Thanks! If you need anything from me let me know!

**Comment by josegomez** [comment] 2020-04-13 21:46
@Mrjelly13 do a pull again on my secondary project and test it. It should work now.
I made a PR to our main project too

**Comment by Mrjelly13** [comment] 2020-04-13 22:07
@josegomez  That did it! Thanks! At least with the test. I'll let you know once the PR goes through.

**Comment by josegomez** [comment] 2020-04-13 23:10
cool @Mrjelly13  as soon as @alexhauser looks at thr PR we can merge it and the fix will be in the next release which should be out pretty soon too

**Closed as completed** 2020-04-14 13:11 UTC
Labels: bug
