### ISSUE TITLE
Can't back out of Import Identity

### ISSUE THREAD

**Issue by wls** [sqrldev/SQRLDotNetClient#120] opened 2020-04-16 19:38 UTC
From the Import Identity dialog, pressing Cancel result in an error of "Error importing textual identity: Value cannot be null. (Parameter 'source')"  ...pressing OK takes you back to the Import Identity.  So, if you don't have one, you can't exit back to the main screen.

Note that Next is enabled, so it's clickable, but without anything in the box, take you no where.

I got to this screen initially thinking it was wanting my rescue code, but couldn't get back out.

Had to force quit.

<img width="399" alt="Screen Shot 2020-04-16 at 3 33 21 PM" src="https://user-images.githubusercontent.com/537381/79499015-4a192400-7ff8-11ea-9bbf-d2b8ab152ece.png">

<img width="401" alt="Screen Shot 2020-04-16 at 3 34 00 PM" src="https://user-images.githubusercontent.com/537381/79499028-51d8c880-7ff8-11ea-8cc6-b0ed1a5485fa.png">

**Comment by alexhauser** [comment] 2020-04-16 19:45
This might already be fixed in master, but I'll have to investigate. Thanks for reporting, @wls!

**Comment by alexhauser** [comment] 2020-04-16 20:06
I can't reproduce this on Windows with the latest source version. 

@josegomez, maybe you can test on macOS: Remove all identities, enter the "Import identity" screen and try backing out using "Cancel".  Anything going south for you?

@wls, only enabling "Next" when either a file was chosen or a textual identity was provided would indeed make sense, I'll implement this at the next opportunity.

**Comment by wls** [comment] 2020-04-16 20:11
Quick thoughts since you'll be on that screen... (though this is an entirely different issue)

The Import file wants a .sqrl file, but the iOS app is currently exporting .sqrlc files.  Renaming its file works, btw.

The Import File ought to either read Import .sqrl, specifically stating what it's looking for, or be more forgiving allowing .sqrl* or even any extension.  It shouldn't be hard to tell if the file was valid or not -- since someone could, in theory, make an invalid file with the right extension and it'd have to be caught.

Never could figure out what to put in the Textual Identity area, as when I copy'n'pasted the contents of the ".sqrlc" file (before reading the source), it rejected the content. No explanation as to what it didn't like.

**Comment by josegomez** [comment] 2020-04-16 20:36
@alexhauser I got it. the issue is in our "prior view" logic.
You should be able to replicate in windows too. We have setup the mainwindow to track Content and PriorContent
And when we switch Content it automatically updates PriorContent with the prior view. The issue is that if we type in some random code in the TextualIdentity and click next, we'll get an error Dialog (which becomes CurrentContent) but that makes ImportIdentity prior content.
When you click OK in the error dialog CurrnetContent and PriorContent are now the same (ImportIdentity)
So when you click Cancel you just go to "PriorContent" which is ImportIdentity....
I hope that makes sense, and yes we need to fix this probably in a few places.

**Comment by alexhauser** [comment] 2020-04-16 20:36
@wls , are you sure that the file extension is `*.sqrlc`, not `sqrc` (no "l")?
The difference between a `*.sqrl` and a `*.sqrc` file is that the former contains all the identity blocks, while the latter only contains block 2 for maximum safety - it will therefore require the rescue code to import such a file.

I'll look into supporting `*.sqrc` files, we should have all the plumbing for that, we only need to expose it in the UI.

**Comment by josegomez** [comment] 2020-04-16 20:39
I believe I tackled this before with the ProgressDialog by making the ProgressDialog an exception case on the Setter for CurrentContent. We probably need to add MessageBox to that too.

See MainWindowVIewModel.cs 26

**Comment by alexhauser** [comment] 2020-04-16 20:40
@wls, regarding the textual identity, this is the textual representation of the identity that you get when you print the identity from the GRC client for example. This has nothing to do with the `*.sqrl` or `*.sqrc` files. See https://www.grc.com/sqrl/SQRL_Cryptography.pdf page 28 for details.

**Comment by alexhauser** [comment] 2020-04-16 20:43
Thanks for the pointers @josegomez, I've already got the "enable/disable next" going and will include the fix for the issue you've described tomorrow - need to get some rest now.

**Comment by wls** [comment] 2020-04-16 20:44
@josegomez -- You just described my first scenario, I tried to put my identity's password in the box, hit Next, it rejected it, then realized I borked things up. Sounds like you figured out the edge-case path that messes with the prior context.

@alexhauser -- Yes, just confirmed it with the latest iOS SQRL beta; exported and Air Dropped it to my iMac. The file -does- show up as a .sqrlc file, which I suspect it should be one extension or the other, not both combined. Put another way, not being a SQRL expert, but based on how you described the two files, I suspect it's an iOS bug.

**Comment by wls** [comment] 2020-04-16 20:49
> ..., this is the textual representation of the identity that you get when you print the identity from the GRC client for example.

Sure enough, found out when I "print" rather than export, it does generate that text. Thank you for the clarification, @alexhauser, and for helping to direct to that part of the documentation. I figured the hex codes from the files was what it wanted.  Nope...!

**Comment by wls** [comment] 2020-04-16 20:54
While we're talking dialog buttons and paths, the Export Identity seems to have both a Back and Done button that each return the Main Menu.  Not sure what the difference between the two would be.

**Comment by alexhauser** [comment] 2020-04-16 20:59
> While we're talking dialog buttons and paths, the Export Identity seems to have both a Back and Done button that each return the Main Menu. Not sure what the difference between the two would be.

We use this screen in more than one scenarios. When you come from the main screen, the "Back" button does not make sense, you're right. In other scenarios, this screen is the last screen in a "wizard" style workflow, there it makes sense. But you're right, we could hide that button when coming directly from the main screen.

Thanks for your suggestions @wls, very much appreciated!

**Comment by josegomez** [comment] 2020-04-16 21:00
go to bed @alexhauser! 😁😋

**Closed as completed** 2020-04-17 18:43 UTC
Labels: bug, question
